/* Generated song group: man */
const songsDataMan = [
 {   name: "棉胎2敏敏唱",
    src: "music/manman/棉胎2敏敏唱.mp3",
    cover: "covers/man35.jpg",
    cat: "man"},
 {   name: "Beat it痴線敏唱",
    src: "music/manman/Beat it痴線敏唱.mp3",
    cover: "covers/man7.jpg",
    cat: "man"},
  {  name: "First love 國語敏唱",
    src: "music/manman/First love 國語敏唱.mp3",
    cover: "covers/man2.jpg",
    cat: "man"},
  {  name: "Rainbow Connecrtion man",
    src: "music/manman/Rainbow Connecrtion man.mp3",
    cover: "covers/man5.jpg",
    cat: "man"},
{   name: "天命最高敏唱",
    src: "music/manman/天命最高敏唱.mp3",
    cover: "covers/man9.jpg",
    cat: "man"},
{   name: "心有獨鍾鋼琴敏唱",
    src: "music/manman/心有獨鍾鋼琴敏唱.mp3",
    cover: "covers/man4.jpg",
    cat: "man"},
  {  name: "心裡日記敏唱",
    src: "music/manman/心裡日記敏唱.mp3",
    cover: "covers/man3.jpg",
    cat: "man"},
  { name: "水瓶座敏唱",
    src: "music/manman/水瓶座敏唱.mp3",
    cover: "covers/man5.jpg",
    cat: "man"},
  {  name: "你的甜蜜敏唱",
    src: "music/manman/你的甜蜜敏唱.mp3",
    cover: "covers/man5.jpg",
    cat: "man"},
{    name: "別裝傻敏唱",
    src: "music/manman/別裝傻敏唱.mp3",
    cover: "covers/man9.jpg",
    cat: "man"},
  {  name: "夜還未深敏唱",
    src: "music/manman/夜還未深敏唱.mp3",
    cover: "covers/man1.jpg",
    cat: "man"},
{   name: "幸運是我敏唱",
    src: "music/manman/幸運是我敏唱.mp3",
    cover: "covers/man4.jpg",
    cat: "man"},
  {  name: "思覺失調敏唱2",
    src: "music/manman/思覺失調敏唱2.mp3",
    cover: "covers/man5.jpg",
    cat: "man"},
{   name: "真情流露鋼琴敏唱",
    src: "music/manman/真情流露鋼琴敏唱.mp3",
    cover: "covers/man1.jpg",
    cat: "man"},
 {   name: "追憶敏唱",
    src: "music/manman/追憶敏唱.mp3",
    cover: "covers/man8.jpg",
    cat: "man"},
 
 {   name: "從來沒有這麼愛戀過敏唱",
    src: "music/manman/從來沒有這麼愛戀過敏唱.mp3",
    cover: "covers/man7.jpg",
    cat: "man"},
 
  {  name: "棉胎敏唱",
    src: "music/manman/棉胎敏唱.mp3",
    cover: "covers/man5.jpg",
    cat: "man"},
 {  name: "結他背脊唱情歌敏唱",
    src: "music/manman/結他背脊唱情歌敏唱.mp3",
    cover: "covers/man2.jpg",
    cat: "man"},
{   name: "結他背脊唱情歌敏唱2",
    src: "music/manman/結他背脊唱情歌敏唱2.mp3",
    cover: "covers/man4.jpg",
    cat: "man"},
 {   name: "愛情是一種法國甜品敏唱",
    src: "music/manman/愛情是一種法國甜品敏唱.mp3",
    cover: "covers/man2.jpg",
    cat: "man"},
{   name: "當我知道你們相愛敏唱",
    src: "music/manman/當我知道你們相愛敏唱.mp3",
    cover: "covers/man9.jpg",
    cat: "man"},
 {   name: "I wanna be with you",
    src: "music/manman/I wanna be with you.mp3",
    cover: "covers/man7.jpg",
    cat: "man"},
  {  name: "My name is d billion kid song",
    src: "music/manman/My name is d billion kid song.mp3",
    cover: "covers/man2.jpg",
    cat: "man"},
  {  name: "Twins 串燒",
    src: "music/manman/Twins 串燒.mp3",
    cover: "covers/man5.jpg",
    cat: "man"},
{   name: "We wish you a merry christmas",
    src: "music/manman/We wish you a merry christmas.mp3",
    cover: "covers/man9.jpg",
    cat: "man"},
{   name: "小叮噹",
    src: "music/manman/小叮噹.mp3",
    cover: "covers/man4.jpg",
    cat: "man"},
  {  name: "五十年之後",
    src: "music/manman/五十年之後.mp3",
    cover: "covers/man3.jpg",
    cat: "man"},
  { name: "五十年以后(敏唱)",
    src: "music/manman/五十年以后(敏唱).mp3",
    cover: "covers/man5.jpg",
    cat: "man"},
  {  name: "午夜情",
    src: "music/manman/午夜情.mp3",
    cover: "covers/man5.jpg",
    cat: "man"},
{    name: "心痛",
    src: "music/manman/心痛.mp3",
    cover: "covers/man9.jpg",
    cat: "man"},
  {  name: "心滿意足(敏唱)",
    src: "music/manman/心滿意足(敏唱).mp3",
    cover: "covers/man1.jpg",
    cat: "man"},
{   name: "他不適合妳",
    src: "music/manman/他不適合妳.mp3",
    cover: "covers/man4.jpg",
    cat: "man"},
  {  name: "未曾心愛已無情",
    src: "music/manman/未曾心愛已無情.mp3",
    cover: "covers/man5.jpg",
    cat: "man"},
{   name: "永遠的微笑敏唱",
    src: "music/manman/永遠的微笑敏唱.mp3",
    cover: "covers/man1.jpg",
    cat: "man"},
 {   name: "白恤衫",
    src: "music/manman/白恤衫.mp3",
    cover: "covers/man8.jpg",
    cat: "man"},
 
 {   name: "好想你2.0",
    src: "music/manman/好想你2.0.mp3",
    cover: "covers/man7.jpg",
    cat: "man"},
 
  {  name: "如果陽光",
    src: "music/manman/如果陽光.mp3",
    cover: "covers/man5.jpg",
    cat: "man"},
 {  name: "孖寶668",
    src: "music/manman/孖寶668.mp3",
    cover: "covers/man2.jpg",
    cat: "man"},
{   name: "有你明白我(敏唱)",
    src: "music/manman/有你明白我(敏唱).mp3",
    cover: "covers/man4.jpg",
    cat: "man"},
 {   name: "死啦啲青春豆",
    src: "music/manman/死啦啲青春豆.mp3",
    cover: "covers/man2.jpg",
    cat: "man"},
{   name: "你你你為了愛情",
    src: "music/manman/你你你為了愛情.mp3",
    cover: "covers/man9.jpg",
    cat: "man"},
  {  name: "我心中有你(敏唱)",
    src: "music/manman/我心中有你(敏唱).mp3",
    cover: "covers/man1.jpg",
    cat: "man"},
  {  name: "我的歌病版(豐唱)",
    src: "music/manman/我的歌病版(豐唱).mp3",
    cover: "covers/man9.jpg",
    cat: "man"},
  {  name: "幸福車站",
    src: "music/manman/幸福車站.mp3",
    cover: "covers/man8.jpg",
    cat: "man"},
  {  name: "易愛難收",
    src: "music/manman/易愛難收.mp3",
    cover: "covers/man5.jpg",
    cat: "man"},
{   name: "花火",
    src: "music/manman/花火.mp3",
    cover: "covers/man6.jpg",
    cat: "man"},
{   name: "長夜My love goodnight",
    src: "music/manman/長夜My love goodnight.mp3",
    cover: "covers/man7.jpg",
    cat: "man"},
{   name: "長相廝守",
    src: "music/manman/長相廝守.mp3",
    cover: "covers/man8.jpg",
    cat: "man"},
{ name: "會錯意敏唱",
  src: "music/manman/會錯意敏唱.mp3",
  cover: "covers/man7.jpg",
  cat: "man"},
{ name: "鄭伊健串燒",
  src: "music/manman/鄭伊健串燒.mp3",
  cover: "covers/man5.jpg",
  cat: "man"},
{ name: "鄭伊健串燒2",
  src: "music/manman/鄭伊健串燒2.mp3",
  cover: "covers/man6.jpg",
  cat: "man"},
{ name: "凝望(敏唱)",
  src: "music/manman/凝望(敏唱).mp3",
  cover: "covers/man8.jpg",
  cat: "man"},
{ name: "擋不住的風情",
  src: "music/manman/擋不住的風情.mp3",
  cover: "covers/man9.jpg",
  cat: "man"},
{ name: "騷靈情歌(敏唱)",
  src: "music/manman/騷靈情歌(敏唱).mp3",
  cover: "covers/man7.jpg",
  cat: "man"},
{ name: "讓昨天再見",
  src: "music/manman/讓昨天再見.mp3",
  cover: "covers/man1.jpg",
  cat: "man"},
{ name: "趙學而串燒(敏唱)",
  src: "music/manman/趙學而串燒(敏唱).mp3",
  cover: "covers/man2.jpg",
  cat: "man"},
{ name: "相聚一刻",
  src: "music/manman/相聚一刻.mp3",
  cover: "covers/man5.jpg",
  cat: "man"},
{ name: "美麗之最(敏唱)",
  src: "music/manman/美麗之最(敏唱).mp3",
  cover: "covers/man8.jpg",
  cat: "man"},
{ name: "祝福你(敏唱)",
  src: "music/manman/祝福你(敏唱).mp3",
  cover: "covers/man3.jpg",
  cat: "man"},
{ name: "閃著淚光慢慢決定",
  src: "music/manman/閃著淚光慢慢決定.mp3",
  cover: "covers/man5.jpg",
  cat: "man"},
{ name: "張敬軒串燒",
  src: "music/manman/張敬軒串燒.mp3",
  cover: "covers/man7.jpg",
  cat: "man"},
{ name: "喇叭牌",
  src: "music/manman/喇叭牌.mp3",
  cover: "covers/man3.jpg",
  cat: "man"},
{ name: "最美的第七天敏",
  src: "music/manman/最美的第七天敏.mp3",
  cover: "covers/man4.jpg",
  cat: "man"},
{ name: "最愛是誰",
  src: "music/manman/最愛是誰.mp3",
  cover: "covers/man5.jpg",
  cat: "man"},
{ name: "開始戀愛(敏唱)",
  src: "music/manman/開始戀愛(敏唱).mp3",
  cover: "covers/man1.jpg",
  cat: "man"},
{ name: "Donki蟹之歌敏唱",
  src: "music/manman/Donki蟹之歌敏唱.mp3",
  cover: "covers/man1.jpg",
  cat: "man"},
{ name: "Hurt So Bad敏唱",
  src: "music/manman/Hurt So Bad敏唱.mp3",
  cover: "covers/man8.jpg",
  cat: "man"},
{ name: "RU王菲串燒敏唱",
  src: "music/manman/RU王菲串燒敏唱.mp3",
  cover: "covers/man3.jpg",
  cat: "man"},
{ name: "RU譚詠麟串燒敏唱",
  src: "music/manman/RU譚詠麟串燒敏唱.mp3",
  cover: "covers/man5.jpg",
  cat: "man"},
{ name: "三個字敏唱",
  src: "music/manman/三個字敏唱.mp3",
  cover: "covers/man7.jpg",
  cat: "man"},
{ name: "天氣會變敏唱",
  src: "music/manman/天氣會變敏唱.mp3",
  cover: "covers/man3.jpg",
  cat: "man"},
{ name: "最美的第七天敏",
  src: "music/manman/最美的第七天敏.mp3",
  cover: "covers/man4.jpg",
  cat: "man"},
{ name: "心的接觸敏唱",
  src: "music/manman/心的接觸敏唱.mp3",
  cover: "covers/man5.jpg",
  cat: "man"},
{ name: "心滿意足敏唱",
  src: "music/manman/心滿意足敏唱.mp3",
  cover: "covers/man1.jpg",
  cat: "man"},
{ name: "只會因你唱敏唱",
  src: "music/manman/只會因你唱敏唱.mp3",
  cover: "covers/man1.jpg",
  cat: "man"},
{ name: "沒有忘掉的面容敏唱",
  src: "music/manman/沒有忘掉的面容敏唱.mp3",
  cover: "covers/man1.jpg",
  cat: "man"},
{ name: "辛尼哥哥串燒",
  src: "music/manman/辛尼哥哥串燒.mp3",
  cover: "covers/man8.jpg",
  cat: "man"},
{ name: "幸運鈴聲敏唱",
  src: "music/manman/幸運鈴聲敏唱.mp3",
  cover: "covers/man3.jpg",
  cat: "man"},
{ name: "思覺失調敏唱",
  src: "music/manman/思覺失調敏唱.mp3",
  cover: "covers/man5.jpg",
  cat: "man"},
{ name: "飛敏唱",
  src: "music/manman/飛敏唱.mp3",
  cover: "covers/man49.jpg",
  cat: "man"},
{ name: "從你眼中敏唱",
  src: "music/manman/從你眼中敏唱.mp3",
  cover: "covers/man46.jpg",
  cat: "man"},
{ name: "情深的眼晴敏唱",
  src: "music/manman/情深的眼晴敏唱.mp3",
  cover: "covers/man43.jpg",
  cat: "man"},
{ name: "情深的眼晴敏唱2",
  src: "music/manman/情深的眼晴敏唱2.mp3",
  cover: "covers/man39.jpg",
  cat: "man"},
{ name: "愛你躲你敏唱",
  src: "music/manman/愛你躲你敏唱.mp3",
  cover: "covers/man37.jpg",
  cat: "man"},
{ name: "噚晚有隻狗仔叫",
  src: "music/manman/噚晚有隻狗仔叫.mp3",
  cover: "covers/man42.jpg",
  cat: "man"}

];
