/* Generated song group: other */
const songsDataOther = [
 { name: "我失戀你悲傷2", src: "music/我失戀你悲傷2.mp3", cover: "covers/cover36.jpg", cat: "slow songs" },
    { name: "扮靚仔", src: "music/扮靚仔.mp3", cover: "covers/cover33.jpg", cat: "fast songs" },
    { name: "明星之歌", src: "music/明星之歌.mp3", cover: "covers/cover35.jpg", cat: "opera" },
    { name: "雨季不再來", src: "music/雨季不再來.mp3", cover: "covers/cover38.jpg", cat: "slow songs" },
    { name: "黃金戰士", src: "music/黃金戰士.mp3", cover: "covers/cover40.jpg", cat: "kids" },
    { name: "愛情蝙蝠俠", src: "music/愛情蝙蝠俠.mp3", cover: "covers/cover34.jpg", cat: "fast songs" },
    { name: "一步一生", src: "music/一步一生.mp3", cover: "covers/cover29.jpg", cat: "slow songs" },
    { name: "時間做證", src: "music/時間做證.mp3", cover: "covers/cover28.jpg", cat: "slow songs" },
    { name: "追憶2", src: "music/追憶2.mp3", cover: "covers/cover30.jpg", cat: "slow songs" },
    { name: "怎麼天生不是女", src: "music/怎麼天生不是女.mp3", cover: "covers/cover16.jpg", cat: "fast songs" },
    { name: "let go", src: "music/let go.mp3", cover: "covers/man13.jpg", cat: "female" },
    { name: "三個字", src: "music/三個字.mp3", cover: "covers/man12.jpg", cat: "slow songs" },
    { name: "今生不再現場", src: "music/今生不再現場.mp3", cover: "covers/cover11.jpg", cat: "slow songs" },
    { name: "不灰鞋", src: "music/不灰鞋.mp3", cover: "covers/cover16.jpg", cat: "other" },
    { name: "一隻蚊", src: "music/一隻蚊.mp3", cover: "covers/cover22.jpg", cat: "fast songs" },
    { name: "七小福", src: "music/七小福.mp3", cover: "covers/cover15.jpg", cat: "kids" },
    { name: "今生今世", src: "music/今生今世.mp3", cover: "covers/cover13.jpg", cat: "slow songs" },
    { name: "分分鐘記起", src: "music/分分鐘記起.mp3", cover: "covers/cover14.jpg", cat: "slow songs" },
    { name: "天外有天", src: "music/天外有天.mp3", cover: "covers/cover26.jpg", cat: "other" },
    { name: "天各一方", src: "music/天各一方.mp3", cover: "covers/cover21.jpg", cat: "slow songs" },
    { name: "心滿意足", src: "music/心滿意足.mp3", cover: "covers/cover20.jpg", cat: "female" },
    { name: "月亮", src: "music/月亮.mp3", cover: "covers/cover23.jpg", cat: "female" },
    { name: "水瓶座", src: "music/水瓶座.mp3", cover: "covers/man15.jpg", cat: "slow songs" },
    { name: "他喜歡的是你", src: "music/他喜歡的是你.mp3", cover: "covers/man10.jpg", cat: "female" },
    { name: "只因我太痴", src: "music/只因我太痴.mp3", cover: "covers/man11.jpg", cat: "slow songs" },
    { name: "只有你不知道", src: "music/只有你不知道.mp3", cover: "covers/man14.jpg", cat: "slow songs" },
    { name: "只屬於我們的一天", src: "music/只屬於我們的一天.mp3", cover: "covers/cover9.jpg", cat: "slow songs" },
    { name: "平常心", src: "music/平常心.mp3", cover: "covers/cover3.jpg", cat: "slow songs" },
    { name: "打開你未來", src: "music/打開你未來.mp3", cover: "covers/cover1.jpg", cat: "fast songs" },
    { name: "未完的小說", src: "music/未完的小說.mp3", cover: "covers/cover6.jpg", cat: "female" },
    { name: "白石嶺公園", src: "music/白石嶺公園.mp3", cover: "covers/cover2.jpg", cat: "kids" },
    { name: "印象", src: "music/印象.mp3", cover: "covers/cover5.jpg", cat: "slow songs" },
    { name: "夢中見", src: "music/夢中見.mp3", cover: "covers/man13.jpg", cat: "slow songs" },
    { name: "情深緣淺", src: "music/情深緣淺.mp3", cover: "covers/man12.jpg", cat: "slow songs" },
    { name: "心裡日記", src: "music/心裡日記.mp3", cover: "covers/cover25.jpg", cat: "slow songs" },
    { name: "戀愛預告", src: "music/戀愛預告.mp3", cover: "covers/cover11.jpg", cat: "slow songs" },
    { name: "世界會變得很美", src: "music/世界會變得很美.mp3", cover: "covers/cover16.jpg", cat: "slow songs" },
    { name: "Beat it痴線", src: "music/Beat it痴線.mp3", cover: "covers/cover22.jpg", cat: "fast songs" },
    { name: "愛到發燒", src: "music/愛到發燒.mp3", cover: "covers/cover15.jpg", cat: "fast songs" },
    { name: "動地驚天愛戀過", src: "music/動地驚天愛戀過.mp3", cover: "covers/cover13.jpg", cat: "slow songs" },
    { name: "春夏秋冬", src: "music/春夏秋冬.mp3", cover: "covers/cover14.jpg", cat: "slow songs" },
    { name: "今生不再", src: "music/今生不再.mp3", cover: "covers/cover26.jpg", cat: "slow songs" },
    { name: "焚情", src: "music/焚情.mp3", cover: "covers/cover21.jpg", cat: "slow songs" },
    { name: "誰叫我", src: "music/誰叫我.mp3", cover: "covers/cover20.jpg", cat: "slow songs" },
    { name: "七十二變", src: "music/七十二變.mp3", cover: "covers/cover23.jpg", cat: "fast songs" },
    { name: "只要為我愛一天", src: "music/只要為我愛一天.mp3", cover: "covers/man15.jpg", cat: "slow songs" },
    { name: "如果可以再見你", src: "music/如果可以再見你.mp3", cover: "covers/man10.jpg", cat: "slow songs" },
    { name: "也曾相識", src: "music/也曾相識.mp3", cover: "covers/man11.jpg", cat: "slow songs" },
    { name: "緊急聯絡人", src: "music/緊急聯絡人.mp3", cover: "covers/man14.jpg", cat: "slow songs" },
    { name: "一千個願意", src: "music/一千個願意.mp3", cover: "covers/cover9.jpg", cat: "slow songs" },
    { name: "遲來的春天", src: "music/遲來的春天.mp3", cover: "covers/cover3.jpg", cat: "slow songs" },
    { name: "感情的段落", src: "music/感情的段落.mp3", cover: "covers/cover1.jpg", cat: "female" },
    { name: "愛情是一種法國甜品", src: "music/愛情是一種法國甜品.mp3", cover: "covers/cover6.jpg", cat: "female" },
    { name: "痛哭", src: "music/痛哭.mp3", cover: "covers/cover2.jpg", cat: "slow songs" },
    { name: "最後的信仰", src: "music/最後的信仰.mp3", cover: "covers/cover5.jpg", cat: "female" },
    { name: "雪中情", src: "music/雪中情.mp3", cover: "covers/cover8.jpg", cat: "slow songs" },
    { name: "迷戀", src: "music/迷戀.mp3", cover: "covers/cover1.jpg", cat: "slow songs" },
    { name: "記得", src: "music/記得.mp3", cover: "covers/cover1.jpg", cat: "slow songs" },
    { name: "真情流露", src: "music/真情流露.mp3", cover: "covers/cover2.jpg", cat: "slow songs" },
    { name: "相對無言", src: "music/相對無言.mp3", cover: "covers/cover4.jpg", cat: "slow songs" },
    { name: "為何仍剩我一人", src: "music/為何仍剩我一人.mp3", cover: "covers/cover2.jpg", cat: "slow songs" },
    { name: "柔情蜜意", src: "music/柔情蜜意.mp3", cover: "covers/cover1.jpg", cat: "slow songs" },
    { name: "明目張膽", src: "music/明目張膽.mp3", cover: "covers/cover3.jpg", cat: "female" },
    { name: "我是你未來", src: "music/我是你未來.mp3", cover: "covers/cover7.jpg", cat: "slow songs" },
    { name: "吻感", src: "music/吻感.mp3", cover: "covers/cover6.jpg", cat: "slow songs" },
    { name: "你狠心來傷我嗎", src: "music/你狠心來傷我嗎.mp3", cover: "covers/cover1.jpg", cat: "slow songs" },
    { name: "再渡艷陽天", src: "music/再渡艷陽天.mp3", cover: "covers/cover2.jpg", cat: "female" },
    { name: "心有獨鍾(鋼琴版)", src: "music/心有獨鍾(鋼琴版).mp3", cover: "covers/cover3.jpg", cat: "slow songs" },
    { name: "不要哭了", src: "music/不要哭了.mp3", cover: "covers/cover1.jpg", cat: "slow songs" },
    { name: "千年女王", src: "music/千年女王.mp3", cover: "covers/cover3.jpg", cat: "kids" },
    { name: "千年女王(傳說)", src: "music/千年女王(傳說).mp3", cover: "covers/cover5.jpg", cat: "kids" },
    { name: "飄零燕", src: "music/飄零燕.mp3", cover: "covers/cover8.jpg", cat: "kids" },
    { name: "1874", src: "music/1874.mp3", cover: "covers/cover5.jpg", cat: "slow songs" },
    { name: "Sol4", src: "music/Sol4.mp3", cover: "covers/cover3.jpg", cat: "slow songs" },
    { name: "一憶三千八天", src: "music/一憶三千八天.mp3", cover: "covers/cover2.jpg", cat: "slow songs" },
    { name: "不見不散", src: "music/不見不散.mp3", cover: "covers/cover4.jpg", cat: "slow songs" },
    { name: "你給我自信", src: "music/你給我自信.mp3", cover: "covers/cover1.jpg", cat: "fast songs" },
    { name: "告訴我你會在夢境中等我", src: "music/告訴我你會在夢境中等我.mp3", cover: "covers/cover7.jpg", cat: "slow songs" },
    { name: "我心不死", src: "music/我心不死.mp3", cover: "covers/cover2.jpg", cat: "female" },
    { name: "我的親愛還是你", src: "music/我的親愛還是你.mp3", cover: "covers/cover6.jpg", cat: "slow songs" },
    { name: "我這樣愛你", src: "music/我這樣愛你.mp3", cover: "covers/cover7.jpg", cat: "slow songs" },
    { name: "我愛玫瑰園", src: "music/我愛玫瑰園.mp3", cover: "covers/cover8.jpg", cat: "fast songs" },
    { name: "沒有你的愛", src: "music/沒有你的愛.mp3", cover: "covers/cover1.jpg", cat: "slow songs" },
    { name: "初戀", src: "music/初戀.mp3", cover: "covers/cover5.jpg", cat: "female" },
    { name: "這一曲送給你", src: "music/這一曲送給你.mp3", cover: "covers/cover7.jpg", cat: "slow songs" },
    { name: "送你一瓣的雪花", src: "music/送你一瓣的雪花.mp3", cover: "covers/cover3.jpg", cat: "slow songs" },
    { name: "假的戀愛", src: "music/假的戀愛.mp3", cover: "covers/cover4.jpg", cat: "female" },
    { name: "富士山下", src: "music/富士山下.mp3", cover: "covers/cover3.jpg", cat: "slow songs" },
    { name: "棉胎", src: "music/棉胎.mp3", cover: "covers/cover6.jpg", cat: "female" },
    { name: "無心快語", src: "music/無心快語.mp3", cover: "covers/cover7.jpg", cat: "fast songs" },
    { name: "給自己的情書", src: "music/給自己的情書.mp3", cover: "covers/cover4.jpg", cat: "female" },
    { name: "媽咪與天父", src: "music/媽咪與天父.mp3", cover: "covers/cover8.jpg", cat: "festival" },
    { name: "暸解你的所有", src: "music/暸解你的所有.mp3", cover: "covers/cover2.jpg", cat: "slow songs" },
    { name: "離開請關燈", src: "music/離開請關燈.mp3", cover: "covers/cover3.jpg", cat: "female" },
    { name: "魔法奇緣之媽媽知道", src: "music/魔法奇緣之媽媽知道.mp3", cover: "covers/cover5.jpg", cat: "kids" },
    { name: "灰姑娘", src: "music/灰姑娘.mp3", cover: "covers/man13.jpg", cat: "female" },
    { name: "但願你明白", src: "music/但願你明白.mp3", cover: "covers/man12.jpg", cat: "female" },
    { name: "你的淺笑", src: "music/你的淺笑.mp3", cover: "covers/cover25.jpg", cat: "slow songs" },
       { name: "我失戀你悲傷", src: "music/我失戀你悲傷.mp3", cover: "covers/cover16.jpg", cat: "slow songs" },
    { name: "我和你", src: "music/我和你.mp3", cover: "covers/cover22.jpg", cat: "slow songs" },
    { name: "我的另一半", src: "music/我的另一半.mp3", cover: "covers/cover15.jpg", cat: "slow songs" },
    { name: "我的感覺", src: "music/我的感覺.mp3", cover: "covers/cover13.jpg", cat: "slow songs" },
    { name: "我還可以真的嗎", src: "music/我還可以真的嗎.mp3", cover: "covers/cover14.jpg", cat: "other" },
    { name: "求你講清楚", src: "music/求你講清楚.mp3", cover: "covers/cover26.jpg", cat: "slow songs" },
    { name: "取我西經", src: "music/取我西經.mp3", cover: "covers/cover21.jpg", cat: "fast songs" },
    { name: "夜夜念奴嬌", src: "music/夜夜念奴嬌.mp3", cover: "covers/cover20.jpg", cat: "slow songs" },
    { name: "夜機", src: "music/夜機.mp3", cover: "covers/cover23.jpg", cat: "female" },
    { name: "夜還未深", src: "music/夜還未深.mp3", cover: "covers/man15.jpg", cat: "slow songs" },
    { name: "怕去屋企找你", src: "music/怕去屋企找你.mp3", cover: "covers/man10.jpg", cat: "other" },
    { name: "明天仍要繼續", src: "music/明天仍要繼續.mp3", cover: "covers/man11.jpg", cat: "slow songs" },
    { name: "法術烏魔多", src: "music/法術烏魔多.mp3", cover: "covers/man14.jpg", cat: "kids" },
    { name: "長髮", src: "music/長髮.mp3", cover: "covers/cover9.jpg", cat: "slow songs" },
    { name: "相識非偶然", src: "music/相識非偶然.mp3", cover: "covers/cover3.jpg", cat: "slow songs" },
    { name: "飛", src: "music/飛.mp3", cover: "covers/cover1.jpg", cat: "slow songs" },
    { name: "怯", src: "music/怯.mp3", cover: "covers/cover6.jpg", cat: "female" },
    { name: "夏日傾情", src: "music/夏日傾情.mp3", cover: "covers/cover2.jpg", cat: "slow songs" },
    { name: "時光倒流二十年", src: "music/時光倒流二十年.mp3", cover: "covers/cover5.jpg", cat: "slow songs" },
    { name: "真的愛情定可到未來", src: "music/真的愛情定可到未來.mp3", cover: "covers/man13.jpg", cat: "slow songs" },
    { name: "真情流露（超時空要塞主題曲）", src: "music/真情流露（超時空要塞主題曲）.mp3", cover: "covers/man12.jpg", cat: "female" },
    { name: "迷惘", src: "music/迷惘.mp3", cover: "covers/cover25.jpg", cat: "slow songs" },
    { name: "追憶", src: "music/追憶.mp3", cover: "covers/cover30.jpg", cat: "slow songs" },
    { name: "從心去愛你", src: "music/從心去愛你.mp3", cover: "covers/cover16.jpg", cat: "slow songs" },
    { name: "從沒這麼愛戀過2011年重新演繹", src: "music/從沒這麼愛戀過2011年重新演繹.mp3", cover: "covers/cover22.jpg", cat: "slow songs" },
    { name: "情緣(阿Sir早晨插曲)", src: "music/情緣(阿Sir早晨插曲).mp3", cover: "covers/cover15.jpg", cat: "slow songs" },
    { name: "欲斷難斷", src: "music/欲斷難斷.mp3", cover: "covers/cover13.jpg", cat: "female" },
    { name: "深情的眼睛", src: "music/深情的眼睛.mp3", cover: "covers/cover14.jpg", cat: "slow songs" },
    { name: "甜蜜十六歲", src: "music/甜蜜十六歲.mp3", cover: "covers/cover26.jpg", cat: "fast songs" },
    { name: "陳慧嫻串燒", src: "music/陳慧嫻串燒.mp3", cover: "covers/cover21.jpg", cat: "female" },
    { name: "幾許風雨", src: "music/幾許風雨.mp3", cover: "covers/cover20.jpg", cat: "slow songs" },
    { name: "晴天陰天雨天", src: "music/晴天陰天雨天.mp3", cover: "covers/cover23.jpg", cat: "slow songs" },
    { name: "開心華之里", src: "music/開心華之里.mp3", cover: "covers/man15.jpg", cat: "fast songs" },
    { name: "開始戀愛", src: "music/開始戀愛.mp3", cover: "covers/man10.jpg", cat: "slow songs" },
    { name: "傷感的戀人", src: "music/傷感的戀人.mp3", cover: "covers/man11.jpg", cat: "slow songs" },
    { name: "愛上你之後", src: "music/愛上你之後.mp3", cover: "covers/man14.jpg", cat: "slow songs" },
    { name: "愛不完", src: "music/愛不完.mp3", cover: "covers/cover9.jpg", cat: "slow songs" },
    { name: "愛在陽光空氣中", src: "music/愛在陽光空氣中.mp3", cover: "covers/cover3.jpg", cat: "slow songs" },
    { name: "傻女", src: "music/傻女.mp3", cover: "covers/cover1.jpg", cat: "female" },
    { name: "溫暖的家", src: "music/溫暖的家.mp3", cover: "covers/cover6.jpg", cat: "fast songs" },
    { name: "愛的替身", src: "music/愛的替身.mp3", cover: "covers/cover2.jpg", cat: "slow songs" },
    { name: "獅子王Hakuna Matata", src: "music/獅子王Hakuna Matata.mp3", cover: "covers/cover5.jpg", cat: "kids" },
    { name: "儂本多情", src: "music/儂本多情.mp3", cover: "covers/cover8.jpg", cat: "slow songs" },
    { name: "糊塗情感", src: "music/糊塗情感.mp3", cover: "covers/cover1.jpg", cat: "slow songs" },
    { name: "醉迷人是您", src: "music/醉迷人是您.mp3", cover: "covers/cover1.jpg", cat: "slow songs" },
    { name: "餘情未了", src: "music/餘情未了.mp3", cover: "covers/cover2.jpg", cat: "slow songs" },
    { name: "舊情人", src: "music/舊情人.mp3", cover: "covers/cover4.jpg", cat: "slow songs" },
    { name: "雜念", src: "music/雜念.mp3", cover: "covers/cover2.jpg", cat: "slow songs" },
    { name: "獻出激情", src: "music/獻出激情.mp3", cover: "covers/cover1.jpg", cat: "fast songs" },
    { name: "鄧麗君串燒", src: "music/鄧麗君串燒.mp3", cover: "covers/cover3.jpg", cat: "female" },
    { name: "聽不到的說話", src: "music/聽不到的說話.mp3", cover: "covers/cover7.jpg", cat: "slow songs" },
    { name: "聽海粵", src: "music/聽海粵.mp3", cover: "covers/cover6.jpg", cat: "female" },
    { name: "薩拉熱窩的羅密歐與茱麗葉", src: "music/薩拉熱窩的羅密歐與茱麗葉.mp3", cover: "covers/cover2.jpg", cat: "female" },
    { name: "給女兒的說話", src: "music/給女兒的說話.mp3", cover: "covers/cover7.jpg", cat: "slow songs" },
];
