/* Generated song group: manman */
const songsDataManman = [
{  name: "Let go2合",
    src: "music/安眠/Let go2合.mp3",
    cover: "covers/man18.jpg",
    cat: "manman"},
 {   name: "Let go合",
    src: "music/安眠/Let go合.mp3",
    cover: "covers/man28.jpg",
    cat: "manman"},
  {  name: "我的歌合生日歌",
    src: "music/安眠/我的歌合生日歌.mp3",
    cover: "covers/man33.jpg",
    cat: "manman"},
  { name: "細水長流合",
    src: "music/安眠/細水長流合.mp3",
    cover: "covers/man24.jpg",
    cat: "manman"},
 {   name: "棉胎合生日之歌",
    src: "music/安眠/棉胎合生日之歌.mp3",
    cover: "covers/man34.jpg",
    cat: "manman"},
{    name: "想思河畔粵合",
    src: "music/安眠/想思河畔粵合.mp3",
    cover: "covers/man21.jpg",
    cat: "manman"},
{  name: "合緊急聯絡人",
    src: "music/安眠/合緊急聯絡人.mp3",
    cover: "covers/man17.jpg",
    cat: "manman"},
 {   name: "閉目入神",
    src: "music/安眠/閉目入神.mp3",
    cover: "covers/cover19.jpg",
    cat: "manman"},
  {  name: "合玻璃之情",
    src: "music/安眠/合玻璃之情.mp3",
    cover: "covers/man9.jpg",
    cat: "manman"},
  { name: "合為你鍾情",
    src: "music/安眠/合為你鍾情.mp3",
    cover: "covers/man11.jpg",
    cat: "manman"},
 {   name: "合也曾相識",
    src: "music/安眠/合也曾相識.mp3",
    cover: "covers/man3.jpg",
    cat: "manman"},
{    name: "三十日",
    src: "music/安眠/三十日.mp3",
    cover: "covers/man1.jpg",
    cat: "manman"},
 {   name: "天荒愛未老",
    src: "music/安眠/天荒愛未老.mp3",
    cover: "covers/man6.jpg",
    cat: "manman"},
  {  name: "合永遠的微笑",
    src: "music/安眠/合永遠的微笑.mp3",
    cover: "covers/man3.jpg",
    cat: "manman"},
  { name: "沒有你的愛",
    src: "music/安眠/沒有你的愛.mp3",
    cover: "covers/man9.jpg",
    cat: "manman"},
 {   name: "晴天陰天雨天",
    src: "music/安眠/晴天陰天雨天.mp3",
    cover: "covers/man5.jpg",
    cat: "manman"},
 {   name: "無時空之戀",
    src: "music/安眠/無時空之戀.mp3",
    cover: "covers/man8.jpg",
    cat: "manman"},

{  name: "合First love 粵",
    src: "music/安眠/合First love 粵.mp3",
    cover: "covers/man17.jpg",
    cat: "manman"},
 {   name: "合Today",
    src: "music/安眠/合Today.mp3",
    cover: "covers/cover19.jpg",
    cat: "manman"},
  {  name: "合一千個願意",
    src: "music/安眠/合一千個願意.mp3",
    cover: "covers/man9.jpg",
    cat: "manman"},
  { name: "合一天一天",
    src: "music/安眠/合一天一天.mp3",
    cover: "covers/man11.jpg",
    cat: "manman"},
 {   name: "合也曾相識2",
    src: "music/安眠/合也曾相識2.mp3",
    cover: "covers/man3.jpg",
    cat: "manman"},
{    name: "合月亮代表我的心",
    src: "music/安眠/合月亮代表我的心.mp3",
    cover: "covers/man1.jpg",
    cat: "manman"},
 {   name: "合水瓶座",
    src: "music/安眠/合水瓶座.mp3",
    cover: "covers/man6.jpg",
    cat: "manman"},
  {  name: "合奶茶加糖",
    src: "music/安眠/合奶茶加糖.mp3",
    cover: "covers/man3.jpg",
    cat: "manman"},
 {   name: "合用背脊唱情歌2",
    src: "music/安眠/合用背脊唱情歌2.mp3",
    cover: "covers/man5.jpg",
    cat: "manman"},
{  name: "合任何天氣",
    src: "music/安眠/合任何天氣.mp3",
    cover: "covers/man17.jpg",
    cat: "manman"},
 {   name: "合狂串樂基兒",
    src: "music/安眠/合狂串樂基兒.mp3",
    cover: "covers/cover19.jpg",
    cat: "manman"},
  {  name: "合赤裸的秘密2",
    src: "music/安眠/合赤裸的秘密2.mp3",
    cover: "covers/man9.jpg",
    cat: "manman"},
  { name: "合奇洛李維斯回信",
    src: "music/安眠/合奇洛李維斯回信.mp3",
    cover: "covers/man11.jpg",
    cat: "manman"},
 {   name: "合明知故犯2",
    src: "music/安眠/合明知故犯2.mp3",
    cover: "covers/man3.jpg",
    cat: "manman"},
{    name: "合花店",
    src: "music/安眠/合花店.mp3",
    cover: "covers/man1.jpg",
    cat: "manman"},
 {   name: "合玻璃之情2",
    src: "music/安眠/合玻璃之情2.mp3",
    cover: "covers/man6.jpg",
    cat: "manman"},
  {  name: "合這麼近那麼遠",
    src: "music/安眠/合這麼近那麼遠.mp3",
    cover: "covers/man3.jpg",
    cat: "manman"},
  { name: "合幾分鐘的約會",
    src: "music/安眠/合幾分鐘的約會.mp3",
    cover: "covers/man9.jpg",
    cat: "manman"},
 {   name: "合游龍戲鳳",
    src: "music/安眠/合游龍戲鳳.mp3",
    cover: "covers/man5.jpg",
    cat: "manman"},
{  name: "合無時空之戀2",
    src: "music/安眠/合無時空之戀2.mp3",
    cover: "covers/man17.jpg",
    cat: "manman"},
 {   name: "合無聲仿有聲",
    src: "music/安眠/合無聲仿有聲.mp3",
    cover: "covers/cover19.jpg",
    cat: "manman"},
  {  name: "合畫紙上的戒指2",
    src: "music/安眠/合畫紙上的戒指2.mp3",
    cover: "covers/man9.jpg",
    cat: "manman"},
  { name: "合會過去的",
    src: "music/安眠/合會過去的.mp3",
    cover: "covers/man11.jpg",
    cat: "manman"},
 {   name: "合粵語新年歌串燒",
    src: "music/安眠/合粵語新年歌串燒.mp3",
    cover: "covers/man3.jpg",
    cat: "manman"},
{    name: "合夢境成真",
    src: "music/安眠/合夢境成真.mp3",
    cover: "covers/man1.jpg",
    cat: "manman"},
 {   name: "合聽海粵",
    src: "music/安眠/合聽海粵.mp3",
    cover: "covers/man6.jpg",
    cat: "manman"},
  {  name: "合美味天王Mamma",
    src: "music/安眠/合美味天王Mamma.mp3",
    cover: "covers/man3.jpg",
    cat: "manman"},
  { name: "合新年快樂",
    src: "music/安眠/合新年快樂.mp3",
    cover: "covers/man9.jpg",
    cat: "manman"},

 {   name: "合C3PO",
    src: "music/安眠/合C3PO.mp3",
    cover: "covers/cover19.jpg",
    cat: "manman"},
  {  name: "合天變地變情不變",
    src: "music/安眠/合天變地變情不變.mp3",
    cover: "covers/man9.jpg",
    cat: "manman"},
  { name: "合世紀末煙花",
    src: "music/安眠/合世紀末煙花.mp3",
    cover: "covers/man11.jpg",
    cat: "manman"},
 {   name: "合只想你會意",
    src: "music/安眠/合只想你會意.mp3",
    cover: "covers/man3.jpg",
    cat: "manman"},
{    name: "合只會因你唱",
    src: "music/安眠/合只會因你唱.mp3",
    cover: "covers/man1.jpg",
    cat: "manman"},
 {   name: "合未曾深愛已無情",
    src: "music/安眠/合未曾深愛已無情.mp3",
    cover: "covers/man6.jpg",
    cat: "manman"},
  {  name: "合用背脊唱情歌",
    src: "music/安眠/合用背脊唱情歌.mp3",
    cover: "covers/man3.jpg",
    cat: "manman"},
  { name: "合好戲之人",
    src: "music/安眠/合好戲之人.mp3",
    cover: "covers/man9.jpg",
    cat: "manman"},
 {   name: "合好戲之人2",
    src: "music/安眠/合好戲之人2.mp3",
    cover: "covers/man5.jpg",
    cat: "manman"},
 {   name: "合有緣的話",
    src: "music/安眠/合有緣的話.mp3",
    cover: "covers/man8.jpg",
    cat: "manman"},
 {   name: "合你的我",
    src: "music/安眠/合你的我.mp3",
    cover: "covers/cover19.jpg",
    cat: "manman"},
  {  name: "合沒名字的歌，無名字的你",
    src: "music/安眠/合沒名字的歌，無名字的你.mp3",
    cover: "covers/man9.jpg",
    cat: "manman"},
  { name: "合赤裸的秘密",
    src: "music/安眠/合赤裸的秘密.mp3",
    cover: "covers/man11.jpg",
    cat: "manman"},
 {   name: "合取消資格",
    src: "music/安眠/合取消資格.mp3",
    cover: "covers/man3.jpg",
    cat: "manman"},
{    name: "合相愛很難",
    src: "music/安眠/合相愛很難.mp3",
    cover: "covers/man1.jpg",
    cat: "manman"},
 {   name: "合秋意中等我",
    src: "music/安眠/合秋意中等我.mp3",
    cover: "covers/man6.jpg",
    cat: "manman"},
  {  name: "合美麗之最",
    src: "music/安眠/合美麗之最.mp3",
    cover: "covers/man3.jpg",
    cat: "manman"},
  { name: "合飛花",
    src: "music/安眠/合飛花.mp3",
    cover: "covers/man9.jpg",
    cat: "manman"},
 {   name: "合留給最愛的說話",
    src: "music/安眠/合留給最愛的說話.mp3",
    cover: "covers/man5.jpg",
    cat: "manman"},
 {   name: "合高山低谷",
    src: "music/安眠/合高山低谷.mp3",
    cover: "covers/man8.jpg",
    cat: "manman"},
 {   name: "合從你眼中",
    src: "music/安眠/合從你眼中.mp3",
    cover: "covers/cover19.jpg",
    cat: "manman"},
  {  name: "合情人知已",
    src: "music/安眠/合情人知已.mp3",
    cover: "covers/man9.jpg",
    cat: "manman"},
  { name: "合情義兩心堅",
    src: "music/安眠/合情義兩心堅.mp3",
    cover: "covers/man11.jpg",
    cat: "manman"},
 {   name: "合望星星",
    src: "music/安眠/合望星星.mp3",
    cover: "covers/man3.jpg",
    cat: "manman"},
{    name: "合梨渦淺笑",
    src: "music/安眠/合梨渦淺笑.mp3",
    cover: "covers/man1.jpg",
    cat: "manman"},
 {   name: "合喜帖街",
    src: "music/安眠/合喜帖街.mp3",
    cover: "covers/man6.jpg",
    cat: "manman"},
  {  name: "合最愛",
    src: "music/安眠/合最愛.mp3",
    cover: "covers/man3.jpg",
    cat: "manman"},
  { name: "合最愛是誰",
    src: "music/安眠/合最愛是誰.mp3",
    cover: "covers/man9.jpg",
    cat: "manman"},
 {   name: "合越吻越傷心",
    src: "music/安眠/合越吻越傷心.mp3",
    cover: "covers/man5.jpg",
    cat: "manman"},
 {   name: "合愛在陽光空氣中",
    src: "music/安眠/合愛在陽光空氣中.mp3",
    cover: "covers/man8.jpg",
    cat: "manman"},
 {   name: "合愛的故事下集",
    src: "music/安眠/合愛的故事下集.mp3",
    cover: "covers/cover19.jpg",
    cat: "manman"},
  {  name: "合愛是永恆",
    src: "music/安眠/合愛是永恆.mp3",
    cover: "covers/man9.jpg",
    cat: "manman"},
  { name: "合愛是這樣甜",
    src: "music/安眠/合愛是這樣甜.mp3",
    cover: "covers/man11.jpg",
    cat: "manman"},
 {   name: "合遊樂場",
    src: "music/安眠/合遊樂場.mp3",
    cover: "covers/man3.jpg",
    cat: "manman"},
{    name: "合遙遠的他",
    src: "music/安眠/合遙遠的他.mp3",
    cover: "covers/man1.jpg",
    cat: "manman"},
 {   name: "合醉紅塵",
    src: "music/安眠/合醉紅塵.mp3",
    cover: "covers/man6.jpg",
    cat: "manman"},
  {  name: "合錫晒你",
    src: "music/安眠/合錫晒你.mp3",
    cover: "covers/man3.jpg",
    cat: "manman"},
  { name: "合櫻花樹下",
    src: "music/安眠/合櫻花樹下.mp3",
    cover: "covers/man9.jpg",
    cat: "manman"},
 {   name: "合歡樂今宵",
    src: "music/安眠/合歡樂今宵.mp3",
    cover: "covers/man5.jpg",
    cat: "manman"},
 {   name: "載歌載舞&詐肚痛",
    src: "music/安眠/載歌載舞&詐肚痛.mp3",
    cover: "covers/man8.jpg",
    cat: "manman"},
 {   name: "合紅茶館",
    src: "music/安眠/合紅茶館.mp3",
    cover: "covers/man10.jpg",
    cat: "manman"},
 {   name: "情非首爾",
    src: "music/manman/情非首爾.mp3",
    cover: "covers/man4.jpg",
    cat: "manman"},
  {  name: "有了你",
    src: "music/manman/有了你.mp3",
    cover: "covers/man1.jpg",
    cat: "manman"},
{   name: "一往情深",
    src: "music/manman/一往情深.mp3",
    cover: "covers/man8.jpg",
    cat: "manman"},
 {   name: "一家笑口",
    src: "music/manman/一家笑口.mp3",
    cover: "covers/man2.jpg",
    cat: "manman"},
{   name: "只怕不再遇上",
    src: "music/manman/只怕不再遇上.mp3",
    cover: "covers/man6.jpg",
    cat: "manman"},
 {  name: "目黑",
    src: "music/manman/目黑.mp3",
    cover: "covers/man9.jpg",
    cat: "manman"},
 {  name: "那裡天空不下雨",
    src: "music/manman/那裡天空不下雨.mp3",
    cover: "covers/man2.jpg",
    cat: "manman"},
  {  name: "那誰",
    src: "music/manman/那誰.mp3",
    cover: "covers/man3.jpg",
    cat: "manman"},
{   name: "來夜方長",
    src: "music/manman/來夜方長.mp3",
    cover: "covers/man4.jpg",
    cat: "manman"},
{   name: "刻不容緩",
    src: "music/manman/刻不容緩.mp3",
    cover: "covers/man5.jpg",
    cat: "manman"},
 {   name: "刻不容緩2",
    src: "music/manman/刻不容緩2.mp3",
    cover: "covers/man7.jpg",
    cat: "manman"},
{   name: "明天你是否依然愛我",
    src: "music/manman/明天你是否依然愛我.mp3",
    cover: "covers/man2.jpg",
    cat: "manman"},
 {   name: "明明白白我的心",
    src: "music/manman/明明白白我的心.mp3",
    cover: "covers/man3.jpg",
    cat: "manman"},
  {  name: "明知故犯",
    src: "music/manman/明知故犯.mp3",
    cover: "covers/man4.jpg",
    cat: "manman"},
  { name: "First love 粵",
    src: "music/manman/First love 粵.mp3",
    cover: "covers/man8.jpg",
    cat: "manman"},
 {   name: "一天一天",
    src: "music/manman/一天一天.mp3",
    cover: "covers/man1.jpg",
    cat: "manman"},
  {  name: "一生不變",
    src: "music/manman/一生不變.mp3",
    cover: "covers/man6.jpg",
    cat: "manman"},
 {  name: "一生愛你一個",
    src: "music/manman/一生愛你一個.mp3",
    cover: "covers/man3.jpg",
    cat: "manman"},
  {  name: "一萬年",
    src: "music/manman/一萬年.mp3",
    cover: "covers/man9.jpg",
    cat: "manman"},
{    name: "沒有你的愛",
    src: "music/manman/沒有你的愛.mp3",
    cover: "covers/man9.jpg",
    cat: "manman"},
 {  name: "不老的傳說",
    src: "music/manman/不老的傳說.mp3",
    cover: "covers/man8.jpg",
    cat: "manman"},
 {   name: "不想獨自快樂",
    src: "music/manman/不想獨自快樂.mp3",
    cover: "covers/man7.jpg",
    cat: "manman"},
 {   name: "五十年以后粵",
    src: "music/manman/五十年以后粵.mp3",
    cover: "covers/man1.jpg",
    cat: "manman"},
  {  name: "仍能情深愛上",
    src: "music/manman/仍能情深愛上.mp3",
    cover: "covers/man6.jpg",
    cat: "manman"},
{   name: "天變地變情不變",
    src: "music/manman/天變地變情不變.mp3",
    cover: "covers/man7.jpg",
    cat: "manman"},
 {   name: "太陽花",
    src: "music/manman/太陽花.mp3",
    cover: "covers/man4.jpg",
    cat: "manman"},
  {  name: "心仍是冷",
    src: "music/manman/心仍是冷.mp3",
    cover: "covers/man1.jpg",
    cat: "manman"},
  {  name: "心淡",
    src: "music/manman/心淡.mp3",
    cover: "covers/man5.jpg",
    cat: "manman"},
 {   name: "心債",
    src: "music/manman/心債.mp3",
    cover: "covers/man4.jpg",
    cat: "manman"},
  {  name: "月半小夜曲",
    src: "music/manman/月半小夜曲.mp3",
    cover: "covers/man7.jpg",
    cat: "manman"},
 {  name: "只屬於我們的一天",
    src: "music/manman/只屬於我們的一天.mp3",
    cover: "covers/man7.jpg",
    cat: "manman"},
  {  name: "未曾心愛已無情2",
    src: "music/manman/未曾心愛已無情2.mp3",
    cover: "covers/man3.jpg",
    cat: "manman"},
 {  name: "如果天空要下雨",
    src: "music/manman/如果天空要下雨.mp3",
    cover: "covers/man6.jpg",
    cat: "manman"},
  {  name: "灰姑娘",
    src: "music/manman/灰姑娘.mp3",
    cover: "covers/man9.jpg",
    cat: "manman"},
  {  name: "你回來吧",
    src: "music/manman/你回來吧.mp3",
    cover: "covers/man1.jpg",
    cat: "manman"},
{   name: "你的我",
    src: "music/manman/你的我.mp3",
    cover: "covers/man4.jpg",
    cat: "manman"},
 {  name: "你是我今生唯一傳奇",
    src: "music/manman/你是我今生唯一傳奇.mp3",
    cover: "covers/man2.jpg",
    cat: "manman"},
  {  name: "你最珍貴",
    src: "music/manman/你最珍貴.mp3",
    cover: "covers/man9.jpg",
    cat: "manman"},
{   name: "我心中有你",
    src: "music/manman/我心中有你.mp3",
    cover: "covers/man9.jpg",
    cat: "manman"},
 {   name: "我的回憶不是我",
    src: "music/manman/我的回憶不是我.mp3",
    cover: "covers/man2.jpg",
    cat: "manman"},
  {  name: "沒名字的歌無名字的你",
    src: "music/manman/沒名字的歌無名字的你.mp3",
    cover: "covers/man9.jpg",
    cat: "manman"},
  {  name: "沒有你的愛",
    src: "music/manman/沒有你的愛.mp3",
    cover: "covers/man7.jpg",
    cat: "manman"},
{   name: "男人最痛",
    src: "music/manman/男人最痛.mp3",
    cover: "covers/man3.jpg",
    cat: "manman"},
{    name: "男朋友",
    src: "music/manman/男朋友.mp3",
    cover: "covers/man5.jpg",
    cat: "manman"},
 {   name: "身體健康",
    src: "music/manman/身體健康.mp3",
    cover: "covers/man1.jpg",
    cat: "manman"},
 
  {  name: "妳知道我在等妳嗎",
    src: "music/manman/妳知道我在等妳嗎.mp3",
    cover: "covers/man9.jpg",
    cat: "manman"},
{ name: "愛在陽光空氣",
  src: "music/manman/愛在陽光空氣.mp3",
  cover: "covers/man1.jpg",
  cat: "manman"},
{ name: "愛自那天遇上",
  src: "music/manman/愛自那天遇上.mp3",
  cover: "covers/man2.jpg",
  cat: "manman"},
{    name: "放生",
    src: "music/manman/放生.mp3",
    cover: "covers/man1.jpg",
    cat: "manman"},

{ name: "愛妳",
  src: "music/manman/愛妳.mp3",
  cover: "covers/man3.jpg",
  cat: "manman"},

{ name: "愛的太遲",
  src: "music/manman/愛的太遲.mp3",
  cover: "covers/man4.jpg",
  cat: "manman"},
{ name: "開始戀愛",
  src: "music/manman/開始戀愛.mp3",
  cover: "covers/man2.jpg",
  cat: "manman"},

{ name: "傻癡癡",
  src: "music/manman/傻癡癡.mp3",
  cover: "covers/man3.jpg",
  cat: "manman"},

{ name: "傾心",
  src: "music/manman/傾心.mp3",
  cover: "covers/man4.jpg",
  cat: "manman"},

{ name: "愛不釋手",
  src: "music/manman/愛不釋手.mp3",
  cover: "covers/man5.jpg",
  cat: "manman"},
{ name: "愛全為你",
  src: "music/manman/愛全為你.mp3",
  cover: "covers/man6.jpg",
  cat: "manman"},

{ name: "愛全為你2",
  src: "music/manman/愛全為你2.mp3",
  cover: "covers/man7.jpg",
  cat: "manman"},

{ name: "愛在心內暖",
  src: "music/manman/愛在心內暖.mp3",
  cover: "covers/man8.jpg",
  cat: "manman"},

{ name: "愛在心內暖2",
  src: "music/manman/愛在心內暖2.mp3",
  cover: "covers/man9.jpg",
  cat: "manman",},

{ name: "游龍戲鳳",
  src: "music/manman/游龍戲鳳.mp3",
  cover: "covers/man6.jpg",
  cat: "manman"},

{ name: "畫紙上的戒指",
  src: "music/manman/畫紙上的戒指.mp3",
  cover: "covers/man7.jpg",
  cat: "manman"},

{ name: "痛愛",
  src: "music/manman/痛愛.mp3",
  cover: "covers/man8.jpg",
  cat: "manman"},

{ name: "紫玉釵",
  src: "music/manman/紫玉釵.mp3",
  cover: "covers/man9.jpg",
  cat: "manman"},

{ name: "從不喜歡孤單一個",
  src: "music/manman/從不喜歡孤單一個.mp3",
  cover: "covers/man8.jpg",
  cat: "manman"},

{ name: "情未了 (2)",
  src: "music/manman/情未了 (2).mp3",
  cover: "covers/man9.jpg",
  cat: "manman"},

{ name: "情未了",
  src: "music/manman/情未了.mp3",
  cover: "covers/man1.jpg",
  cat: "manman"},

{ name: "情是永願著迷",
  src: "music/manman/情是永願著迷.mp3",
  cover: "covers/man2.jpg",
  cat: "manman"},
{ name: "高山低谷",
  src: "music/manman/高山低谷.mp3",
  cover: "covers/man6.jpg",
  cat: "manman"},
{ name: "秋意中等我",
  src: "music/manman/秋意中等我.mp3",
  cover: "covers/man6.jpg",
  cat: "manman"},

{ name: "美中不足",
  src: "music/manman/美中不足.mp3",
  cover: "covers/man7.jpg",
  cat: "manman"},

{ name: "恭喜你",
  src: "music/manman/恭喜你.mp3",
  cover: "covers/man9.jpg",
  cat: "manman"},

{ name: "留給最愛的說話",
  src: "music/manman/留給最愛的說話.mp3",
  cover: "covers/man1.jpg",
  cat: "manman"},

{ name: "真愛在明天",
  src: "music/manman/真愛在明天.mp3",
  cover: "covers/man2.jpg",
  cat: "manman"},
{ name: "脈搏奔流",
  src: "music/manman/脈搏奔流.mp3",
  cover: "covers/man4.jpg",
  cat: "manman"},
{ name: "難為正邪定分界",
  src: "music/manman/難為正邪定分界.mp3",
  cover: "covers/man5.jpg",
  cat: "manman"},

{ name: "願你待我真的好",
  src: "music/manman/願你待我真的好.mp3",
  cover: "covers/man6.jpg",
  cat: "manman"},

{ name: "護花使者",
  src: "music/manman/護花使者.mp3",
  cover: "covers/man8.jpg",
  cat: "manman"},

{ name: "歡樂年年",
  src: "music/manman/歡樂年年.mp3",
  cover: "covers/man9.jpg",
  cat: "manman"},
{ name: "為你鐘情",
  src: "music/manman/為你鐘情.mp3",
  cover: "covers/man3.jpg",
  cat: "manman"},

{ name: "相愛很難",
  src: "music/manman/相愛很難.mp3",
  cover: "covers/man4.jpg",
  cat: "manman"},
{ name: "難的有情人",
  src: "music/manman/難的有情人.mp3",
  cover: "covers/man4.jpg",
  cat: "manman"},

{ name: "選擇",
  src: "music/manman/選擇.mp3",
  cover: "covers/man1.jpg",
  cat: "manman"},

{ name: "鮮花送玉人",
  src: "music/manman/鮮花送玉人.mp3",
  cover: "covers/man2.jpg",
  cat: "manman"},

{ name: "藍精靈",
  src: "music/manman/藍精靈.mp3",
  cover: "covers/man3.jpg",
  cat: "manman"},
{ name: "餘震",
  src: "music/manman/餘震.mp3",
  cover: "covers/man7.jpg",
  cat: "manman"},
{ name: "歲月如歌",
  src: "music/manman/歲月如歌.mp3",
  cover: "covers/man8.jpg",
  cat: "manman"},

{ name: "滄海遺珠",
  src: "music/manman/滄海遺珠.mp3",
  cover: "covers/man9.jpg",
  cat: "manman"},

{ name: "痴心眼內",
  src: "music/manman/痴心眼內.mp3",
  cover: "covers/man1.jpg",
  cat: "manman"},

{ name: "聖誕串燒",
  src: "music/manman/聖誕串燒.mp3",
  cover: "covers/man2.jpg",
  cat: "manman"},

{ name: "萬千寵愛在一身",
  src: "music/manman/萬千寵愛在一身.mp3",
  cover: "covers/man3.jpg",
  cat: "manman"},

{ name: "夢中天使",
  src: "music/manman/夢中天使.mp3",
  cover: "covers/man5.jpg",
  cat: "manman"},

{ name: "夢想成真",
  src: "music/manman/夢想成真.mp3",
  cover: "covers/man6.jpg",
  cat: "manman"},

{ name: "對你太在乎",
  src: "music/manman/對你太在乎.mp3",
  cover: "covers/man7.jpg",
  cat: "manman"},

{ name: "遙遠的她",
  src: "music/manman/遙遠的她.mp3",
  cover: "covers/man8.jpg",
  cat: "manman"},

{ name: "漣漪",
  src: "music/manman/漣漪.mp3",
  cover: "covers/man9.jpg",
  cat: "manman"},

{ name: "酷愛",
  src: "music/manman/酷愛.mp3",
  cover: "covers/man1.jpg",
  cat: "manman"}
,
{ name: "劇場版赤裸的秘密",
  src: "music/manman/劇場版赤裸的秘密.mp3",
  cover: "covers/man2.jpg",
  cat: "manman"},

{ name: "編舟情歌",
  src: "music/manman/編舟情歌.mp3",
  cover: "covers/man3.jpg",
  cat: "manman"},

{ name: "誰令你心痴",
  src: "music/manman/誰令你心痴.mp3",
  cover: "covers/man4.jpg",
  cat: "manman"},
{   name: "幽媾",
    src: "music/manman/幽媾.mp3",
    cover: "covers/man9.jpg",
    cat: "manman"},

{ name: "愛的故事上集",
  src: "music/manman/愛的故事上集.mp3",
  cover: "covers/man5.jpg",
  cat: "manman"},

{ name: "新的世界 阿拉丁",
  src: "music/manman/新的世界 阿拉丁.mp3",
  cover: "covers/man6.jpg",
  cat: "manman"},
  {  name: "我這一生",
    src: "music/manman/我這一生.mp3",
    cover: "covers/man1.jpg",
    cat: "manman"},
 {   name: "每隔兩秒",
    src: "music/manman/每隔兩秒.mp3",
    cover: "covers/man2.jpg",
    cat: "manman"},
  {  name: "吉慶滿堂",
    src: "music/manman/吉慶滿堂.mp3",
    cover: "covers/man2.jpg",
    cat: "manman"},
{    name: "好心好報",
    src: "music/manman/好心好報.mp3",
    cover: "covers/man6.jpg",
    cat: "manman"},
 {  name: "必殺技",
    src: "music/manman/必殺技.mp3",
    cover: "covers/man2.jpg",
    cat: "manman"},
 {   name: "小老鼠與大花猫(2)",
    src: "music/manman/小老鼠與大花猫(2).mp3",
    cover: "covers/man2.jpg",
    cat: "manman"},
  {  name: "小老鼠與大花猫",
    src: "music/manman/小老鼠與大花猫.mp3",
    cover: "covers/man4.jpg",
    cat: "manman"},
 {  name: "大懶堂",
    src: "music/manman/大懶堂.mp3",
    cover: "covers/man4.jpg",
    cat: "manman"},
 {   name: "找對的人1",
    src: "music/安眠/找對的人1.mp3",
    cover: "covers/man4.jpg",
    cat: "manman"},
{   name: "找對的人2",
    src: "music/安眠/找對的人2.mp3",
    cover: "covers/man5.jpg",
    cat: "manman"},
 {   name: "找對的人3",
    src: "music/安眠/找對的人3.mp3",
    cover: "covers/man6.jpg",
    cat: "manman"},
 {   name: "找對的人4",
    src: "music/安眠/找對的人4.mp3",
    cover: "covers/man7.jpg",
    cat: "manman"},
 {   name: "合RU串燒",
    src: "music/安眠/合RU串燒.mp3",
    cover: "covers/man1.jpg",
    cat: "manman"},
  {  name: "合愛到分離仍是愛",
    src: "music/安眠/合愛到分離仍是愛.mp3",
    cover: "covers/man1.jpg",
    cat: "manman"},
 {   name: "合萬千寵愛在一生",
    src: "music/安眠/合萬千寵愛在一生.mp3",
    cover: "covers/man2.jpg",
    cat: "manman"},
  {  name: "合我恨我是女人",
    src: "music/安眠/合我恨我是女人.mp3",
    cover: "covers/man2.jpg",
    cat: "manman"},
{    name: "合從你眼中2",
    src: "music/安眠/合從你眼中2.mp3",
    cover: "covers/man6.jpg",
    cat: "manman"},
 {  name: "合只因喜歡你",
    src: "music/安眠/合只因喜歡你.mp3",
    cover: "covers/man2.jpg",
    cat: "manman"},
 {   name: "合只有情永在",
    src: "music/安眠/合只有情永在.mp3",
    cover: "covers/man2.jpg",
    cat: "manman"},
  {  name: "合有緣的話2",
    src: "music/安眠/合有緣的話2.mp3",
    cover: "covers/man4.jpg",
    cat: "manman"},
 {  name: "合怯",
    src: "music/安眠/合怯.mp3",
    cover: "covers/man4.jpg",
    cat: "manman"},
 {   name: "合望星星2",
    src: "music/安眠/合望星星2.mp3",
    cover: "covers/man4.jpg",
    cat: "manman"},
{   name: "合合久必婚",
    src: "music/安眠/合合久必婚.mp3",
    cover: "covers/man5.jpg",
    cat: "manman"},
 {   name: "合感激遇到你",
    src: "music/安眠/合感激遇到你.mp3",
    cover: "covers/man6.jpg",
    cat: "manman"},
 {   name: "合問誰領風騷",
    src: "music/安眠/合問誰領風騷.mp3",
    cover: "covers/man7.jpg",
    cat: "manman"},

];
